#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node scripts/validate-commit.mjs "$1"
VALID_MSG=$?

if [ $VALID_MSG -ne 0 ]; then
  exit $VALID_MSG
fi

echo "Commit message valid. Running tests/linting..."

npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed, aborting commit."
  exit 1
fi

echo "Running unit and integration tests..."
npm test
if [ $? -ne 0 ]; then
  echo "Unit/Integration tests failed, aborting commit."
  exit 1
fi

echo "Running coverage..."
npm run test:coverage
if [ $? -ne 0 ]; then
  echo "Coverage failed, aborting commit."
  exit 1
fi